### ISSUE TITLE
Did this ever work?

### ISSUE THREAD

**Issue by bcardarella** [collectiveidea/delayed_job_data_mapper#1]
According to this: http://datamapper.lighthouseapp.com/projects/20609/tickets/1019-built-in-to_yaml-method-gives-anonymous-class-error

DataMapper intentionally returns Hash objects when you YAML.load a #to_yaml DataMapper instance. If that is the case then without explicitly overwriting this method in each class how could the DataMapper backend ever work?

**Comment by stefanobernardi** [comment]
I'm getting a weird expected a time or date, got Fri Jan 14 05:06:19 -0800 2011
error

**Comment by rileydutton** [comment]
I'm getting the same error as stefanobernardi when trying to execute a worker. I can queue up jobs just fine, though. It seems to be something in the active_support library that's being used.

Is there a sample implementation/mini app using this that someone can point me at that is actually working? 

I have also tried this with both SQLite and Postgres backends and both give them same error, btw.

**Comment by stefanobernardi** [comment]
Yeah, you actually need to require "active_support/core_ext"

**Comment by ghost** [comment]
We are seeing the same issue having just update DataMapper to 1.1.0

require'ing active_support/core_ext does not resolve the issue.

**Comment by bcardarella** [comment]
This is never going to work. The DataMapper team override how Ruby YAMLizes objects. I think it is a pretty stupid idea they've implemented. DataMapper dumps a hash of the attributes when you call #to_yaml instead. This ensures the object can never be restored. Blame the DM team on this one.

**Comment by ghost** [comment]
it sounds then like the onus on delayed_job_data_mapper is to reify the object differently (?)

... other than "fixing" the way DM #to_yaml works that is.

**Comment by zlern2k** [comment]
The duck-punch delayed_job_data_mapper includes in lib/delayed/serialization/data_mapper.rb works as long as you don't require dm-serializer, which fortunately is not required by dm-core.

If you are including dm-serializer for some of the other methods but don't use the yaml one, it's easy enough (if gross) to just copy in the files you need or fork and remove yaml; dm-serializer is very simple - basically just 5 files IIRC. If you want the to_yaml behavior that comes with dm-serializer... then I guess that's gonna require a level of monkey patching that we fortunately didn't have to take on.
