### ISSUE TITLE
Support for lasted activesupport versions

### ISSUE THREAD

**Issue by JustDevZero** [collectiveidea/delayed_job_data_mapper#14]
It would be nice to have support for lasted activesupport versions, otherwise this can screw some projects... :(

In snapshot (Gemfile.lock):
activesupport (= 4.2.1)

In Gemfile:
delayed_job_data_mapper (>= 0) ruby depends on 
delayed_job (~> 4.0) ruby depends on 
activesupport (< 5.0, >= 3.0)
ruby
activesupport (>= 0) ruby

delayed_job_data_mapper (>= 0) ruby depends on
dm-active_model (~> 1.0) ruby depends on
activemodel (~> 3.1.0) ruby depends on
activesupport (= 3.1.0) ruby

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-create it by May 17, 2017. Thanks!
