### ISSUE TITLE
datamapper 1.1.0

### ISSUE THREAD

**Issue by basex** [collectiveidea/delayed_job_data_mapper#5]
Please upgrade the Gemfile to make it work with datamapper 1.1.0.
http://datamapper.org/articles/datamapper-110-released.html

**Comment by tpitale** [comment]
This is a pretty old ticket, but in case someone finds it from google.

The gemspec currently specifies `dm-core ~> 1.0`. The latest dm appears to be 1.2.1, and master works with it.
