### ISSUE TITLE
Latest Delayed Job

### ISSUE THREAD

**Issue by tpitale** [collectiveidea/delayed_job_data_mapper#9]
It appears that there is a much newer delayed job (3.0+) but it appears that the gem version of delayed_job_data_mapper is still 1.0.0.rc and is linked to 2.1.4.

I'd like to update this all if I can, but wanted to create this issue to start the discussion.

**Comment by tpitale** [comment]
It appears that the gemspec in master lists the delayed_job dependency as ~> '3.0'. This does not appear to be what gets installed with the released gem. The version specified is still 1.0.0.rc

**Comment by tpitale** [comment]
I've been working on fixing the 12 broken tests. Half the problem was lack of == on resources. One is time math issue.

The rest seem to be serialization issues related to DJ's alias_method_chaining of Psych:

`def visit_Psych_Nodes_Mapping_with_class(object)`

**Comment by tpitale** [comment]
I think I'll need to open a PR in DJ for:

```
    when /^!ruby\/DataMapper:(.+)$/
      klass = resolve_class($1)
      payload = Hash[*object.children.map { |c| accept c }]
      begin
        primary_keys = klass.properties.select { |p| p.key? }
        key_names = primary_keys.map { |p| p.name.to_s }
        klass.get!(*key_names.map { |k| payload["attributes"][k] })
      rescue DataMapper::ObjectNotFoundError
        raise Delayed::DeserializationError
      end
    end
```

**Comment by tpitale** [comment]
2 Failures left.

**Comment by sferik** [comment]
@tpitale Thanks for diving in on this! If you're down to two failures, it would be :candy: if you could make the tests :green_heart: and then open a single pull request. That said, if you'd prefer to do this in two requests, I can merge your fixes now and the remaining fixes separately. It's really up to you.

Thanks again for you work on this!

**Comment by tpitale** [comment]
I'm getting close on the last two failures. The tricky bit is that I'll have a PR for DJ and one for dj_dm, due to the aforementioned psych_ext stuff.

**Comment by tpitale** [comment]
Calling it a night, will hopefully wrap up tomorrow.

**Comment by sferik** [comment]
Sounds good, man.

**Comment by tpitale** [comment]
Opened a PR, closing this issue.

https://github.com/collectiveidea/delayed_job_data_mapper/pull/10
